version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - sync-server

  sync-server:
    build:
      context: .
      dockerfile: apps/sync-server/Dockerfile
    ports:
      - "5858:5858"
    volumes:
      # Sync server rooms data
      - ./apps/sync-server/.rooms:/app/apps/sync-server/.rooms
      - ./apps/sync-server/.assets:/app/apps/sync-server/.assets
